version: '3.7'

services:
  redis:
    image: redislabs/rejson:latest
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "SQLSxrvxr123$"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  # financialapi:
  #   image: [your-dockerhub]/financialapi
  #   environment:
  #     Redis__ConnectionString: "redis:6379"
  #     RabbitMQ__ConnectionString: "rabbitmq://rabbitmq:5672"
  #   depends_on:
  #     - redis
  #     - rabbitmq

  # financialbgtasks:
  #   image: [your-dockerhub]/financialbgtasks
  #   environment:
  #     Redis__ConnectionString: "redis:6379"
  #     RabbitMQ__ConnectionString: "rabbitmq://rabbitmq:5672"
  #   depends_on:
  #     - redis
  #     - rabbitmq

  # newsapi:
  #   image: [your-dockerhub]/newsapi
  #   environment:
  #     Mongo__Url: "mongodb://mongo:27017"
  #     Rabbit__Url: "rabbitmq://rabbitmq"
  #   depends_on:
  #     - mongo
  #     - rabbitmq

  # newsbgtasks:
  #   image: [your-dockerhub]/newsbgtasks
  #   environment:
  #     Mongo__Url: "mongodb://mongo:27017"
  #   depends_on:
  #     - mongo

  # notifications:
  #   image: [your-dockerhub]/notifications
  #   environment:
  #     Mongo__Url: "mongodb://mongo:27017"
  #   depends_on:
  #     - mongo

  mvc:
    image: sk1es/insightify.mvc:v6
    environment:
      IdentityUrl: "http://identityserver:5001"
      GatewayUrl: "http://gateway:5030"
    ports:
      - "5008:80"
    depends_on:
      - gateway
      - identityserver

  gateway:
    image: sk1es/insightify.gateway:v4
    environment:
      ServiceEndpoints__FinancialData: "http://financialapi:5002"
      ServiceEndpoints__News: "http://newsapi:5004"
      ServiceEndpoints__Posts: "http://posts:5036"
      IdentityUrl: "http://identityserver:5001"
    ports:
      - "5030:5030"
    depends_on:
      # - financialapi
      # - financialbgtasks
      # - newsapi
      # - newsbgtasks
      - posts
      # - notifications
      - identityserver

  posts:
    image: sk1es/insightify.posts
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=PostsV1;User Id=sa; Password=SQLSxrvxr123$; TrustServerCertificate=True;"
      IdentityUrl: "http://identityserver:5001"
      ASPNETCORE_URLS: http://+:5036
    ports:
    - "5036:5036"
    depends_on:
      - sqlserver
      - identityserver

  identityserver:
    image: sk1es/insightify.identityserver:v6
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=IdentityApi;User Id=sa; Password=SQLSxrvxr123$; TrustServerCertificate=True;"
    ports:
    - "5001:5001"
    depends_on:
      - sqlserver
