# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    paths: 
      - 'src/Services/Insightify.IdentityAPI/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore src/Services/Insightify.IdentityAPI/Insightify.IdentityAPI/Insightify.IdentityAPI.csproj
    - name: Build
      run: dotnet build src/Services/Insightify.IdentityAPI/Insightify.IdentityAPI/Insightify.IdentityAPI.csproj --no-restore
    - name: Test
      run: dotnet test src/Services/Insightify.IdentityAPI/Insightify.IdentityAPI/Insightify.IdentityAPI.csproj --no-build --verbosity normal
      
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      working-directory: src/Services/Insightify.IdentityAPI/Insightify.IdentityAPI
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: sk1es
          password: orion0713
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: src/Services/Insightify.IdentityAPI/Insightify.IdentityAPI
          file: src/Services/Insightify.IdentityAPI/Insightify.IdentityAPI/Dockerfile
          push: true
          tags: sk1es/insightify.identity
