# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Dockerize Insightify.MVC

on:
  push:
    branches: [ "develop" ]
    paths: 
      - 'src/Web/Insightify.MVC/**'
  pull_request:
    branches: [ "develop" ]
    paths: 
      - 'src/Web/Insightify.MVC/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore src/Web/Insightify.MVC/Insightify.MVC/Insightify.MVC.csproj
    - name: Build
      run: dotnet build src/Web/Insightify.MVC/Insightify.MVC/Insightify.MVC.csproj --no-restore
    - name: Test
      run: dotnet test src/Web/Insightify.MVC/Insightify.MVC/Insightify.MVC.csproj --no-build --verbosity normal
      
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    env:
      working-directory: src/Web/Insightify.MVC/Insightify.MVC
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: src/Web/Insightify.MVC/Insightify.MVC
          file: src/Web/Insightify.MVC/Insightify.MVC/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/insightify.mvc

